"""
Revision ID: b005d9af28f5
Revises: c9d0ad70cfbf
Create Date: 2025-10-31 22:04:18.871777
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b005d9af28f5'
down_revision = 'c9d0ad70cfbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
