"""
Revision ID: c9d0ad70cfbf
Revises:
Create Date: 2025-10-31 19:16:20.686388
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import Integer, String

# revision identifiers, used by Alembic.
revision = 'c9d0ad70cfbf'
down_revision = None
branch_labels = None
depends_on = None


def seed(op):
    # --- Seed Data ---
    staff_table = table(
        'staff',
        column('id', Integer),
        column('name', String),
        column('age', Integer),
        column('position', String)
    )

    duty_table = table(
        'duty_schedule',
        column('date', String),
        column('staff_id', Integer),
    )


    # Insert sample staff
    op.bulk_insert(
        staff_table,
        [
            {'id': 1, 'name': 'Alice', 'age': 28, 'position': 'Nurse'},
            {'id': 2, 'name': 'Bob', 'age': 34, 'position': 'Doctor'},
            {'id': 3, 'name': 'Charlie', 'age': 30, 'position': 'Paramedic'},
        ],
    )

    # Insert duty schedule
    op.bulk_insert(
        duty_table,
        [
            {'date': '2025-11-01', 'staff_id': 1},
            {'date': '2025-11-02', 'staff_id': 2},
            {'date': '2025-11-03', 'staff_id': 3},
        ],
    )



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duty_schedule',
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_index(op.f('ix_duty_schedule_staff_id'), 'duty_schedule', ['staff_id'], unique=False)

    op.create_table('staff',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_name'), 'staff', ['name'], unique=False)
    # ### end Alembic commands ###

    seed(op)


def downgrade() -> None:
    # Remove seeded rows first
    op.execute("DELETE FROM duty_schedule")
    op.execute("DELETE FROM staff")

    # Drop schema objects
    op.drop_index(op.f('ix_staff_name'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_duty_schedule_staff_id'), table_name='duty_schedule')
    op.drop_table('duty_schedule')
